services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Monta o código-fonte para refletir as alterações imediatamente
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: bessa
      POSTGRES_PASSWORD: bessa
      POSTGRES_DB: runningdb
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
